sudo: false
language: python
python:
    - "2.7"
install:
    - pip install flake8
    - pip install atc/atc_thrift/ atc/atcd/ atc/django-atc-api/ atc/django-atc-demo-ui/ atc/django-atc-profile-storage/
script:
    - make python_lint
